### ISSUE TITLE
Processing loop stuck

### ISSUE THREAD

**Issue by gdethier** [pousse-cafe/pousse-cafe#155]
Below a stack trace that caused the processing thread to stop processing.

```
Exception in thread "Processing Thread 1" java.lang.NoSuchMethodError: 'poussecafe.attribute.AdaptingListAttributeWithAdapterBuilder poussecafe.attribute.ListAttributeBuilder.usingItemDataAdapter(poussecafe.attribute.adapters.DataAdapter)'
	<...>
	at poussecafe.domain.Repository.add(Repository.java:116)
	at poussecafe.environment.SingleAggregateCreationMessageConsumer.lambda$addCreatedAggregate$1(SingleAggregateCreationMessageConsumer.java:126)
	at poussecafe.storage.NoTransactionRunner.runInTransaction(NoTransactionRunner.java:7)
	at poussecafe.environment.SingleAggregateCreationMessageConsumer.addCreatedAggregate(SingleAggregateCreationMessageConsumer.java:126)
	at poussecafe.environment.SingleAggregateCreationMessageConsumer.lambda$createAggregate$0(SingleAggregateCreationMessageConsumer.java:86)
	at poussecafe.environment.MessageListenerConsumptionReport$Builder.runAndReport(MessageListenerConsumptionReport.java:150)
	at poussecafe.environment.SingleAggregateCreationMessageConsumer.createAggregate(SingleAggregateCreationMessageConsumer.java:85)
	at poussecafe.environment.SingleAggregateCreationMessageConsumer.consume(SingleAggregateCreationMessageConsumer.java:70)
	at poussecafe.processing.MessageListenerExecutor.executeListener(MessageListenerExecutor.java:96)
	at poussecafe.processing.MessageListenerGroupConsumption.executeInApmTransaction(MessageListenerGroupConsumption.java:144)
	at poussecafe.processing.MessageListenerGroupConsumption.executeCreations(MessageListenerGroupConsumption.java:271)
	at poussecafe.processing.MessageListenerGroupConsumption.execute(MessageListenerGroupConsumption.java:111)
	at poussecafe.processing.MessageListenersGroup.consumeMessageOrRetry(MessageListenersGroup.java:107)
	at poussecafe.processing.MessageConsumption.consumeMessage(MessageConsumption.java:76)
	at poussecafe.processing.MessageConsumption.consumeMessageOrRetryGroup(MessageConsumption.java:69)
	at poussecafe.processing.MessageConsumption.execute(MessageConsumption.java:61)
	at poussecafe.processing.MessageProcessor.processMessage(MessageProcessor.java:44)
	at poussecafe.processing.MessageProcessingThread.processAndSignal(MessageProcessingThread.java:103)
	at poussecafe.processing.MessageProcessingThread.processor(MessageProcessingThread.java:85)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gdethier** [comment]
The bug actually only occurs in the context of the test runtime where of the blocking call to PousseCafeTest.waitUntilAllMessageQueuesEmpty.

**Comment by gdethier** [comment]
Fixed in 28888a814ec58644dd313f2ff871e6b66ec110bc.

**Comment by gdethier** [comment]
Another blocking call is causing issues in TestRuntimeWrapper.submitCommand and TestRuntimeWrapper.submitCommands. The issue only arises when the message processing thread crashes. In that situation, above methods wait endlessly for submitted commands to be processed.

**Comment by gdethier** [comment]
Proper logging of message processing thread's crash is handled in f489d314c7b5392c7c151feae74bd8da59ae180c.
