### ISSUE TITLE
ConcurrentModificationException in test

### ISSUE THREAD

**Issue by gdethier** [pousse-cafe/pousse-cafe#208]
The following stack trace can be seen in logs when using more than 1 processing thread:

```
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at poussecafe.test.PousseCafeTest.catchAll(PousseCafeTest.java:153)
	... 19 common frames omitted
 ```

Using a single processing thread fixes the issue. So a solution is probably to make `PousseCafeTest.catchAll(Message)` synchronized.

**Comment by gdethier** [comment]
It would maybe be more elegant to ensure that listeners are always called in mutual exclusion so that model code base is never crippled with an implementation detail like `synchronized` keyword.

**Comment by gdethier** [comment]
In order to prevent any performance degradation, it was after all decided not to create a mutual exclusion on listeners. Indeed, the only case where this would make sense is when the listener is inside of a service and as services are supposed to be stateless, this should never be necessary. So the particular case of PousseCafeTest (which is stateful) is handled by simply making `catchAll` synchronized.
